project:
  type: website
  output-dir: docs

website:
  title: "Samantha Woods"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd 
      - href: posts.qmd
      - href: Free for All.qmd
      - href: Resume.qmd

format:
  html:
    theme: styles.scss
    toc: true
    mainfont: Playfair Display 
    editor: visual

