project:
  type: website
  output-dir: docs

website:
  title: "Samantha Woods"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd 
      - href: Project.qmd
      - href: Free for All.qmd
      - href: Resume.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

