---
title: "Campus Involvement"
about: 
  links: 
    - text: YCT at UCSB
      href: https://www.yourchildrenstreesatucsb.org/
    - text: Sprout UP at UCSB
      href: https://www.sproutup.org/ucsb
---

I am currently involved in several environmental organizations across campus.

Over the course of my second year at UCSB, I interned with *Your Children’s Trees*, a community-centered organization dedicated to environmental restoration through tree planting.

As an intern, I actively participated in tree planting initiatives at key ecological and community sites, including Ellwood Butterfly Grove, Ellwood Mesa, North Campus Open Space, Isla Vista Elementary School, and private properties in Isla Vista.

In addition to hands-on restoration work, I also helped engage the local community by representing *Your Children’s Trees* at elementary school Science Nights. These events gave us the opportunity to share our knowledge of native trees, ecology, and climate resilience with students and families in a fun, accessible way.



Additionally, I have been involved in *Sprout Up* at UCSB as an instructor. UCSB is home to the largest chapter of *Sprout Up* dedicated to providing environmental education to first and second graders across Goleta. Alongside my teaching team, I introduced topics such as waste management, water conservation, and bee pollination, helping young students build a foundation in sustainability and environmental awareness.



