---
title: "Hair Guide for Sustainable Engagement in the Hair Economy"
format: html
lightbox: auto
title-block-banner: true
categories:
        - zine
about:
    links:
         - text: What is a Zine?
           href: "https://guides.lib.purdue.edu/loudonpaper/what-is-a-zine"
---

For my ENV S 40 course, Critical Thinking and Evidence-Based Reasoning for the Environment, I created a zine titled "Hair Guide for Sustainable Engagement in the Hair Economy ", which explores the environmental impact of synthetic hair commonly used in protective styles by Black women. This project investigates how synthetic hair—produced from plastic—contributes to pollution through toxic chemical emissions during manufacturing and waste accumulation after use.

While synthetic hair is often chosen for its affordability and versatility, its environmental cost is rarely discussed. My goal with this zine was to raise awareness about the ecological footprint of synthetic hair, without vilifying the cultural significance of protective styling. I also included accessible, affordable alternatives and sustainable practices to empower individuals to make informed choices that support both personal expression and environmental health.






